### ISSUE TITLE
Instance primer

### ISSUE THREAD

**Issue by baccenfutter** [blunix/role-aws-ec2#6]
All instances need to be primed:
- [ ] Configure password-less authentication for root
- [ ] Remove the ec2-user
- [ ] Set hostname in /etc/hosts and /etchostname and ensure that it persists across reboots
- [ ] Install and configure unattended-upgrades

**Comment by p-thurner** [comment]
I think it makes sense to install and activate unattended-upgrades as well - in my opinion, instances should never exist without automated security upgrades configured. This way we are absolutely sure that those are configured as soon as the instance creation is finished.
On a sidenote to this, apt-get upgrade should be run at that point once too.

**Comment by p-thurner** [comment]
as in I'm voting for things to stay pretty much the way I wrote them already :P ;) with the addition of fixing the persistent hostname thingy with systemd.
Sidenote: please test if aws does not rewrite /etc/hosts upon stop + start instance.

**Comment by baccenfutter** [comment]
@p-thurner 
Obviously, this can not go into `role-aws-ec2` because that role is executed by the play against `localhost` (boto). Thus, priming instances should take place in a dedicated `instance_primer.yml` play. This play then would have to be executed against each freshly deployed EC2 instance.

Does that sound good to you?

**Comment by p-thurner** [comment]
hmm. I think we need that task at every aws using customer, so I would prefer a role instead of copy paste from playbook to playbook. maybe role-aws-prime?
you are right, role-aws-ec2 isn't ideal for this maybe..

**Comment by baccenfutter** [comment]
Makes sense to me. `role-aws-ec2-prime` it is.

**Comment by p-thurner** [comment]
one more sidenote: if we call this role-prime, we could use it with other providers, like sys11. We would have to parameterize the user the role uses to login, as well as the user that is deleted at the end of the role (sys11 user is called differently, I think ubuntu or sth). I think on aws ubuntu images the default user is also not admin.
If we could then split up the role into two parts, one fix the admin user thingy, the other set hostname and install unattended-upgrades, we could even use it to "prime" profitbricks and hetzner machines.

**Comment by p-thurner** [comment]
maybe we should just make this two roles. One for fixing the initial login user if != root and one for managing the absolute basics, like hostname, unattended-upgrades and so on.

**Comment by baccenfutter** [comment]
I agree this should go into separate roles. But I would suggest to create a dedicated `role-unattended-upgrades`. That is technically a service and should go into a service role included somewhere in the baseline.

Then I would create `role-prime` for user- and hostname-management and implement it in a way that it simply skips a tasks if its variable(s) aren't set (or set to default).

**Comment by p-thurner** [comment]
My idea for splitting user management and the rest was because when you re-execute user-management thingy it can't login as admin@ anymore and it will fail. Hence if we write one role which first logs in as admin@, then sets up hostnames and then deletes the admin user, we wont be able to setup hostnames anymore.

I kinda disagree on role-unattended-upgrades as I'm not sure if its good if we maintain > 100 roles - I dont think the task(s) are enough for a own role. My idea was rather something like a collection of basics tasks, which include things like:
- setting timezone
- unattended-upgrades
- installing haveged (imho every machine should have this)
- setting locales
- installing general packages required on servers

But I see your point in making a role for all (most) of this too.. I'm not sure..

**Comment by p-thurner** [comment]
Less text more suggestions:
- role-fix-initial-cloud-user (better wording required)
- role-basics (with very short one or two task - tasks, like unattended-upgrades, haveged, apt-get upgrade, setting timezone..)

**Comment by baccenfutter** [comment]
https://github.com/blunix/role-pkg
